# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Update Data
permissions:
  contents: write

on: 
  push:
  schedule:
    - cron: "15 19 * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [lts/*]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - name: Update resources
      uses: test-room-7/action-update-file@v2
      with:
          file-path: |
            edges.json
            nodes.json
          commit-msg: Update graph data
          github-token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
